# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphic.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 518)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabwidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabwidget.setGeometry(QtCore.QRect(0, 0, 861, 421))
        self.tabwidget.setStatusTip("")
        self.tabwidget.setAccessibleName("")
        self.tabwidget.setObjectName("tabwidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(350, 10, 113, 22))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(290, 10, 55, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 150, 211, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 150, 61, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(290, 40, 55, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_58.setGeometry(QtCore.QRect(350, 40, 113, 22))
        self.lineEdit_58.setText("")
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_59.setGeometry(QtCore.QRect(350, 70, 113, 22))
        self.lineEdit_59.setText("")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(290, 70, 55, 16))
        self.label_29.setObjectName("label_29")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(350, 100, 111, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(350, 180, 111, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabwidget.addTab(self.tab, "")
        self.TapeZero = QtWidgets.QWidget()
        self.TapeZero.setObjectName("TapeZero")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 50, 191, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.TapeZero)
        self.label_4.setGeometry(QtCore.QRect(50, 110, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.TapeZero)
        self.label_5.setGeometry(QtCore.QRect(230, 110, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.TapeZero)
        self.label_6.setGeometry(QtCore.QRect(380, 110, 31, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 140, 101, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 170, 101, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 200, 101, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 140, 101, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_9.setGeometry(QtCore.QRect(200, 170, 101, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_10.setGeometry(QtCore.QRect(200, 200, 101, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_11.setGeometry(QtCore.QRect(350, 140, 101, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_12.setGeometry(QtCore.QRect(350, 170, 101, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_13.setGeometry(QtCore.QRect(350, 200, 101, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.radioButton = QtWidgets.QRadioButton(self.TapeZero)
        self.radioButton.setGeometry(QtCore.QRect(30, 260, 131, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.TapeZero)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 310, 111, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.TapeZero)
        self.lineEdit_14.setGeometry(QtCore.QRect(350, 240, 91, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_4 = QtWidgets.QPushButton(self.TapeZero)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 50, 93, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.TapeZero)
        self.pushButton_7.setGeometry(QtCore.QRect(350, 280, 91, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton = QtWidgets.QPushButton(self.TapeZero)
        self.pushButton.setGeometry(QtCore.QRect(170, 280, 161, 31))
        self.pushButton.setObjectName("pushButton")
        self.tabwidget.addTab(self.TapeZero, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_44.setGeometry(QtCore.QRect(270, 30, 91, 22))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_45.setGeometry(QtCore.QRect(270, 60, 91, 22))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_46.setGeometry(QtCore.QRect(270, 90, 91, 22))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_47.setGeometry(QtCore.QRect(270, 120, 91, 22))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_48.setGeometry(QtCore.QRect(270, 150, 91, 22))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_49.setGeometry(QtCore.QRect(370, 40, 61, 22))
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_50.setGeometry(QtCore.QRect(370, 70, 61, 22))
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_51.setGeometry(QtCore.QRect(370, 110, 61, 22))
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_52.setGeometry(QtCore.QRect(370, 140, 61, 22))
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_53.setGeometry(QtCore.QRect(470, 60, 71, 22))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_54.setGeometry(QtCore.QRect(470, 90, 71, 22))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_55.setGeometry(QtCore.QRect(470, 120, 71, 22))
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_56.setGeometry(QtCore.QRect(400, 210, 91, 22))
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_57.setGeometry(QtCore.QRect(500, 210, 91, 22))
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(290, 10, 55, 16))
        self.label_23.setObjectName("label_23")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 250, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(252, 250, 121, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_61.setGeometry(QtCore.QRect(70, 50, 91, 22))
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(50, 90, 141, 28))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabwidget.addTab(self.tab_2, "")
        self.Azimuth = QtWidgets.QWidget()
        self.Azimuth.setObjectName("Azimuth")
        self.label_2 = QtWidgets.QLabel(self.Azimuth)
        self.label_2.setGeometry(QtCore.QRect(140, 30, 61, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_15.setGeometry(QtCore.QRect(210, 30, 71, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_16.setGeometry(QtCore.QRect(300, 30, 71, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_17.setGeometry(QtCore.QRect(420, 30, 71, 22))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_7 = QtWidgets.QLabel(self.Azimuth)
        self.label_7.setGeometry(QtCore.QRect(360, 70, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Azimuth)
        self.label_8.setGeometry(QtCore.QRect(360, 90, 61, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_18.setGeometry(QtCore.QRect(420, 70, 71, 22))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_19.setGeometry(QtCore.QRect(420, 90, 71, 22))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_9 = QtWidgets.QLabel(self.Azimuth)
        self.label_9.setGeometry(QtCore.QRect(180, 140, 61, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_20.setGeometry(QtCore.QRect(250, 140, 161, 22))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_21.setGeometry(QtCore.QRect(250, 170, 131, 22))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_22.setGeometry(QtCore.QRect(250, 200, 131, 22))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_23.setGeometry(QtCore.QRect(250, 230, 131, 22))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_24.setGeometry(QtCore.QRect(250, 260, 131, 22))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_25.setGeometry(QtCore.QRect(250, 290, 131, 22))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_26.setGeometry(QtCore.QRect(250, 320, 131, 22))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_10 = QtWidgets.QLabel(self.Azimuth)
        self.label_10.setGeometry(QtCore.QRect(180, 170, 61, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Azimuth)
        self.label_11.setGeometry(QtCore.QRect(180, 200, 61, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Azimuth)
        self.label_12.setGeometry(QtCore.QRect(180, 260, 51, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Azimuth)
        self.label_13.setGeometry(QtCore.QRect(180, 290, 41, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Azimuth)
        self.label_14.setGeometry(QtCore.QRect(180, 320, 61, 21))
        self.label_14.setObjectName("label_14")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.Azimuth)
        self.lineEdit_27.setGeometry(QtCore.QRect(250, 350, 131, 22))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_15 = QtWidgets.QLabel(self.Azimuth)
        self.label_15.setGeometry(QtCore.QRect(180, 350, 61, 21))
        self.label_15.setObjectName("label_15")
        self.label_30 = QtWidgets.QLabel(self.Azimuth)
        self.label_30.setGeometry(QtCore.QRect(180, 230, 61, 21))
        self.label_30.setObjectName("label_30")
        self.tabwidget.addTab(self.Azimuth, "")
        self.Config = QtWidgets.QWidget()
        self.Config.setObjectName("Config")
        self.label_16 = QtWidgets.QLabel(self.Config)
        self.label_16.setGeometry(QtCore.QRect(270, 120, 61, 21))
        self.label_16.setObjectName("label_16")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.Config)
        self.lineEdit_28.setGeometry(QtCore.QRect(350, 120, 91, 22))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_17 = QtWidgets.QLabel(self.Config)
        self.label_17.setGeometry(QtCore.QRect(460, 120, 41, 21))
        self.label_17.setObjectName("label_17")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.Config)
        self.lineEdit_29.setGeometry(QtCore.QRect(350, 150, 91, 22))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.Config)
        self.lineEdit_30.setGeometry(QtCore.QRect(350, 180, 91, 22))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.Config)
        self.lineEdit_31.setGeometry(QtCore.QRect(350, 210, 91, 22))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_18 = QtWidgets.QLabel(self.Config)
        self.label_18.setGeometry(QtCore.QRect(270, 150, 81, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.Config)
        self.label_19.setGeometry(QtCore.QRect(270, 180, 61, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.Config)
        self.label_20.setGeometry(QtCore.QRect(270, 210, 61, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.Config)
        self.label_21.setGeometry(QtCore.QRect(460, 150, 61, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.Config)
        self.label_22.setGeometry(QtCore.QRect(460, 180, 61, 21))
        self.label_22.setObjectName("label_22")
        self.pushButton_5 = QtWidgets.QPushButton(self.Config)
        self.pushButton_5.setGeometry(QtCore.QRect(460, 210, 61, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_24 = QtWidgets.QLabel(self.Config)
        self.label_24.setGeometry(QtCore.QRect(270, 10, 61, 21))
        self.label_24.setObjectName("label_24")
        self.comboBox = QtWidgets.QComboBox(self.Config)
        self.comboBox.setGeometry(QtCore.QRect(350, 10, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_25 = QtWidgets.QLabel(self.Config)
        self.label_25.setGeometry(QtCore.QRect(270, 40, 61, 21))
        self.label_25.setObjectName("label_25")
        self.comboBox_2 = QtWidgets.QComboBox(self.Config)
        self.comboBox_2.setGeometry(QtCore.QRect(350, 40, 73, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_26 = QtWidgets.QLabel(self.Config)
        self.label_26.setGeometry(QtCore.QRect(460, 10, 71, 21))
        self.label_26.setObjectName("label_26")
        self.comboBox_3 = QtWidgets.QComboBox(self.Config)
        self.comboBox_3.setGeometry(QtCore.QRect(460, 40, 73, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton_8 = QtWidgets.QPushButton(self.Config)
        self.pushButton_8.setGeometry(QtCore.QRect(460, 70, 61, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_27 = QtWidgets.QLabel(self.Config)
        self.label_27.setGeometry(QtCore.QRect(270, 70, 61, 21))
        self.label_27.setObjectName("label_27")
        self.comboBox_4 = QtWidgets.QComboBox(self.Config)
        self.comboBox_4.setGeometry(QtCore.QRect(350, 70, 73, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.tabwidget.addTab(self.Config, "")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_60.setGeometry(QtCore.QRect(0, 420, 861, 22))
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(320, 450, 191, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Project"))
        self.pushButton_3.setText(_translate("MainWindow", "Browse"))
        self.label_28.setText(_translate("MainWindow", "Station"))
        self.label_29.setText(_translate("MainWindow", "Target"))
        self.pushButton_9.setText(_translate("MainWindow", "Create Project"))
        self.pushButton_6.setText(_translate("MainWindow", "Load Project"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab), _translate("MainWindow", "Project"))
        self.label_4.setText(_translate("MainWindow", "Left"))
        self.label_5.setText(_translate("MainWindow", "Right"))
        self.label_6.setText(_translate("MainWindow", "MID"))
        self.radioButton.setText(_translate("MainWindow", "Before measure"))
        self.radioButton_2.setText(_translate("MainWindow", "After measure"))
        self.pushButton_4.setText(_translate("MainWindow", "Z Measure"))
        self.pushButton_7.setText(_translate("MainWindow", "Compute"))
        self.pushButton.setText(_translate("MainWindow", "Download the data"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.TapeZero), _translate("MainWindow", "TapeZero"))
        self.label_23.setText(_translate("MainWindow", "Time"))
        self.pushButton_2.setText(_translate("MainWindow", "Compute"))
        self.pushButton_10.setText(_translate("MainWindow", "Download the data"))
        self.pushButton_12.setText(_translate("MainWindow", "Preliminary orientation"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_2), _translate("MainWindow", "PTM"))
        self.label_2.setText(_translate("MainWindow", "Tape Zero"))
        self.label_7.setText(_translate("MainWindow", "E value"))
        self.label_8.setText(_translate("MainWindow", "dw"))
        self.label_9.setText(_translate("MainWindow", "Method"))
        self.label_10.setText(_translate("MainWindow", "Z"))
        self.label_11.setText(_translate("MainWindow", "N\'"))
        self.label_12.setText(_translate("MainWindow", "C"))
        self.label_13.setText(_translate("MainWindow", "E"))
        self.label_14.setText(_translate("MainWindow", "Azimuth"))
        self.label_15.setText(_translate("MainWindow", "TargetDiff"))
        self.label_30.setText(_translate("MainWindow", "ΔN"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.Azimuth), _translate("MainWindow", "Azimuth"))
        self.label_16.setText(_translate("MainWindow", "E value"))
        self.label_17.setText(_translate("MainWindow", "gon"))
        self.label_18.setText(_translate("MainWindow", "dw (equator)"))
        self.label_19.setText(_translate("MainWindow", "Latitude"))
        self.label_20.setText(_translate("MainWindow", "c prop"))
        self.label_21.setText(_translate("MainWindow", "gon"))
        self.label_22.setText(_translate("MainWindow", "dec"))
        self.pushButton_5.setText(_translate("MainWindow", "Apply"))
        self.label_24.setText(_translate("MainWindow", "COM Port"))
        self.comboBox.setItemText(0, _translate("MainWindow", "COM1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COM2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "COM3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "COM4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "COM5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "COM6"))
        self.label_25.setText(_translate("MainWindow", "Protocol"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "GeoCOM"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "GSI-8/16"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Topcon"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "T2002"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Trimble"))
        self.label_26.setText(_translate("MainWindow", "Timer [ms]"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "500"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "750"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "1000"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "1500"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "2500"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "5000"))
        self.pushButton_8.setText(_translate("MainWindow", "Apply"))
        self.label_27.setText(_translate("MainWindow", "Unit"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "GON"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "° (dec.)"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "° (sexa.)"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "MIL"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.Config), _translate("MainWindow", "Config"))
        self.pushButton_11.setText(_translate("MainWindow", "Save Changes"))

